apiVersion: v1
kind: Pod
metadata:
  name: ngnix
  labels: 
    env: test1
spec:
  containers:
    - name: ngnix
      image: saikrishna8341/web-app:v87
      ports:
      - containerPort: 80
      imagePullPolicy: Always
  
   
